---
- name: Create the tng-docker and tng-files directory.
  ansible.builtin.file:
    path: /opt/tng-docker/tng-files
    state: directory
    owner: tng
    group: tng
    mode: '0755'

- name: Create the mariadb directory.
  ansible.builtin.file:
    path: /opt/tng-docker/mariadb
    state: directory
    owner: tng
    group: tng
    mode: '0754'

- name: Install unzip.
  ansible.builtin.apt:
    name:
      - unzip
    state: present

- name: Check if /opt/tng-docker/tng-files is empty
  ansible.builtin.find:
    paths: /opt/tng-docker/tng-files
  register: found_files

- name: Extract the TNG software into /opt/tng-docker/tng-files
  ansible.builtin.unarchive:
    src: 'files/{{ tng_zip }}'
    dest: /opt/tng-docker/tng-files
    owner: tng
    group: '{{ ansible_user }}'
  when: found_files.matched == 0

- name: Copy the required docker files and configs.
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/opt/tng-docker/{{ item.dest }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0744
  loop:
    - src: files/Dockerfile-nginx
      dest: Dockerfile-nginx
    - src: files/Dockerfile-phpfpm
      dest: Dockerfile-phpfpm
    - src: files/nginx.conf
      dest: nginx.conf
    - src: templates/docker-compose.yml.j2
      dest: docker-compose.yml

- name: Ensure monitoring environment is running.
  community.docker.docker_compose_v2:
    project_src: "/opt/tng-docker/"
    build: always
  become: false
