FROM php:8.3-fpm-alpine

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli pdo pdo_mysql

RUN printf 'error_reporting = E_ALL \n\
display_errors = Off \n\
display_startup_errors = On \n\
log_errors = On \n\
error_log = /var/log/php_errors.log \n\
error_reporting = E_ALL \n\
memory_limit = 256M \n\
upload_max_filesize = 64M \n\
post_max_size = 64M' >> /usr/local/etc/php/conf.d/php.ini

RUN mkdir -p /var/log && touch /var/log/php_errors.log

RUN apk add --no-cache \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    freetype-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install gd

RUN apk update \
    && apk add \
        libxml2-dev \
    && docker-php-ext-install -j$(nproc) \
        xml

RUN apk update \
    && apk add \
        oniguruma-dev \
    && docker-php-ext-install -j$(nproc) \
        mbstring